name: "Workflow"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Every week

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout nix repo
      uses: actions/checkout@v4
      with:
        repository: 'llakala/nix' # My fork of nix, auto-updates when nix commits

    - name: Install nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Setup cachix
      uses: cachix/cachix-action@v15
      with:
        name: nix-readline
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build
      run: nix-build
